# ARES Edge System - Unified Configuration
# This file contains runtime configuration parameters for all modules

system:
  name: "ARES Edge System"
  version: "1.0.0"
  mode: "production"  # Options: development, testing, production
  log_level: "info"   # Options: debug, info, warning, error, critical

# GPU Configuration
gpu:
  device_id: 0
  memory_pool_size_mb: 4096
  enable_peer_access: true
  enable_unified_memory: false
  compute_mode: "exclusive"  # Options: default, exclusive, prohibited

# Core System Settings
core:
  quantum_resilience:
    enabled: true
    key_rotation_interval_s: 3600
    pqc_algorithm: "dilithium3"
    backup_algorithm: "falcon512"
  
  neuromorphic:
    enabled: true
    spike_threshold: 1.0
    refractory_period_ms: 2.0
    learning_rate: 0.01
    max_spike_rate_hz: 1000

# CEW (Cyber Electronic Warfare) Configuration
cew:
  enabled: true
  adaptive_jamming:
    enabled: true
    min_frequency_ghz: 0.1
    max_frequency_ghz: 40.0
    power_budget_watts: 100.0
    hop_rate_hz: 10000
  
  spectrum_waterfall:
    fft_size: 1024
    overlap_ratio: 0.5
    window_type: "blackman-harris"
  
  threat_classifier:
    model_path: "/models/threat_classifier_v3.onnx"
    confidence_threshold: 0.85
    max_concurrent_threats: 128

# Swarm Configuration
swarm:
  enabled: true
  max_members: 256
  communication:
    protocol: "byzantine_gossip"
    encryption: "aes256-gcm"
    max_message_size: 4096
  
  consensus:
    algorithm: "pbft"  # Practical Byzantine Fault Tolerance
    timeout_ms: 1000
    max_faulty_nodes_ratio: 0.33
  
  task_auction:
    enabled: true
    bid_timeout_ms: 500
    max_concurrent_auctions: 32

# Countermeasures
countermeasures:
  chaos_induction:
    enabled: true
    confusion_radius_m: 100.0
    signature_manipulation_strength: 0.8
    friendly_fire_prevention: true
  
  last_man_standing:
    enabled: true
    trigger_threshold: 0.9
    survival_priority: "mission_critical"
  
  self_destruct:
    enabled: false  # Requires explicit override
    secure_erase_passes: 7
    thermite_temperature_c: 2500

# Identity Management
identity:
  hot_swap:
    enabled: true
    max_identities: 256
    transition_time_ms: 50
    encryption_algorithm: "chacha20-poly1305"
  
  hardware_attestation:
    enabled: true
    attestation_interval_s: 300
    tpm_version: "2.0"
    secure_boot: true

# Optical Stealth
optical_stealth:
  enabled: true
  metamaterial_control:
    update_rate_hz: 1000
    wavelength_range_nm: [380, 780]  # Visible spectrum
    ir_suppression: true
  
  multi_spectral_fusion:
    bands: ["visible", "nir", "swir", "mwir", "lwir"]
    fusion_algorithm: "wavelet"
  
  rioss:
    enabled: true
    pattern_complexity: "high"

# Digital Twin
digital_twin:
  enabled: true
  simulation:
    physics_engine: "bullet"
    time_step_ms: 1.0
    max_prediction_horizon_s: 10.0
  
  state_sync:
    update_rate_hz: 100
    compression: "lz4"
    encryption: true

# Federated Learning
federated_learning:
  enabled: true
  coordinator:
    aggregation_algorithm: "fedavg"
    min_participants: 3
    round_timeout_s: 60
  
  homomorphic:
    scheme: "ckks"
    poly_modulus_degree: 16384
    scale_bits: 40
  
  secure_multiparty:
    protocol: "spdz"
    max_parties: 32

# Orchestrator
orchestrator:
  chronopath:
    enabled: true
    time_dilation_factor: 1.0
    causality_enforcement: true
  
  drpp:
    redundancy_factor: 3
    path_diversity: 5
    quantum_tunneling: false

# Backscatter Communication
backscatter:
  enabled: true
  communication:
    modulation: "qam16"
    data_rate_kbps: 100
    error_correction: "ldpc"
  
  energy_harvesting:
    enabled: true
    efficiency: 0.7
    storage_capacity_mj: 10.0

# Network Configuration
network:
  interfaces:
    - type: "ethernet"
      name: "eth0"
      mtu: 9000
    - type: "wireless"
      name: "wlan0"
      mode: "monitor"
  
  mesh:
    enabled: true
    protocol: "batman-adv"
    encryption: true

# Security
security:
  encryption:
    algorithm: "aes256-gcm"
    key_derivation: "argon2id"
  
  authentication:
    method: "mutual_tls"
    certificate_path: "/certs/ares.crt"
    key_path: "/certs/ares.key"
  
  intrusion_detection:
    enabled: true
    ml_model: "isolation_forest"

# Logging and Monitoring
logging:
  output: "syslog"
  format: "json"
  rotation:
    enabled: true
    max_size_mb: 100
    max_files: 10
  
  telemetry:
    enabled: true
    endpoint: "https://telemetry.ares.local"
    interval_s: 60

# Performance Tuning
performance:
  cpu:
    affinity: [0, 1, 2, 3]  # CPU cores
    governor: "performance"
  
  memory:
    huge_pages: true
    numa_aware: true
  
  gpu:
    power_limit_watts: 300
    clock_offset_mhz: 100

# Development/Debug Settings
debug:
  enable_profiling: false
  enable_trace: false
  dump_intermediates: false
  simulation_mode: false